import type { UsState } from "./usStates";

/** Indian states & union territories. Largest cities first, mirrors usStates.ts. */
export const INDIA_STATES: UsState[] = [
  { name: "Andhra Pradesh", abbr: "AP", cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"] },
  { name: "Arunachal Pradesh", abbr: "AR", cities: ["Itanagar", "Naharlagun", "Pasighat"] },
  { name: "Assam", abbr: "AS", cities: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"] },
  { name: "Bihar", abbr: "BR", cities: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"] },
  { name: "Chhattisgarh", abbr: "CG", cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"] },
  { name: "Goa", abbr: "GA", cities: ["Panaji", "Margao", "Vasco da Gama", "Mapusa"] },
  { name: "Gujarat", abbr: "GJ", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"] },
  { name: "Haryana", abbr: "HR", cities: ["Faridabad", "Gurugram", "Panipat", "Ambala", "Hisar"] },
  { name: "Himachal Pradesh", abbr: "HP", cities: ["Shimla", "Dharamshala", "Solan", "Mandi"] },
  { name: "Jharkhand", abbr: "JH", cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"] },
  { name: "Karnataka", abbr: "KA", cities: ["Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi"] },
  { name: "Kerala", abbr: "KL", cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"] },
  { name: "Madhya Pradesh", abbr: "MP", cities: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"] },
  { name: "Maharashtra", abbr: "MH", cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad"] },
  { name: "Manipur", abbr: "MN", cities: ["Imphal"] },
  { name: "Meghalaya", abbr: "ML", cities: ["Shillong"] },
  { name: "Mizoram", abbr: "MZ", cities: ["Aizawl"] },
  { name: "Nagaland", abbr: "NL", cities: ["Kohima", "Dimapur"] },
  { name: "Odisha", abbr: "OD", cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur"] },
  { name: "Punjab", abbr: "PB", cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Mohali"] },
  { name: "Rajasthan", abbr: "RJ", cities: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"] },
  { name: "Sikkim", abbr: "SK", cities: ["Gangtok"] },
  { name: "Tamil Nadu", abbr: "TN", cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"] },
  { name: "Telangana", abbr: "TG", cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"] },
  { name: "Tripura", abbr: "TR", cities: ["Agartala"] },
  { name: "Uttar Pradesh", abbr: "UP", cities: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Noida"] },
  { name: "Uttarakhand", abbr: "UK", cities: ["Dehradun", "Haridwar", "Haldwani", "Rishikesh"] },
  { name: "West Bengal", abbr: "WB", cities: ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"] },
  { name: "Delhi", abbr: "DL", cities: ["New Delhi", "Dwarka", "Rohini"] },
  { name: "Jammu and Kashmir", abbr: "JK", cities: ["Srinagar", "Jammu"] },
  { name: "Chandigarh", abbr: "CH", cities: ["Chandigarh"] },
  { name: "Puducherry", abbr: "PY", cities: ["Puducherry", "Karaikal"] },
];
